spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restful_recommend?useSSL=false
    username: root
    password: betty391427
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ##jwt配置
  audience:
    clientId: 098f6bcd4621d373cade4e832627b4f6
    base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
    name: restapiuser
    expiresSecond: 172800