spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restful_recommend?useSSL=false
    username: root
    password: betty391427
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true